dist: trusty
language: java
jdk:
- openjdk8
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- find . -type f -name "*.sh" -exec shellcheck {} \;
script:
- ./run.sh
cache:
  directories:
  - $HOME/.m2
