sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
install:
- java -version && javac -version && mvn -version -B
before_script:
- find . -type f -name "*.sh" -exec shellcheck {} \;
script:
- ./run.sh
